### ISSUE TITLE
Work on Hololens or VR devices?

### ISSUE THREAD

**Issue by justinLifelike** [keijiro/ComputeMarchingCubes#4]
Dear Keijiro,

Do you know if this would work on Hololens 2 or VR devices? 
Thank you for sharing your knowledge! 

Kind Regards!

**Comment by keijiro** [comment]
It might work. If you find issues with those devices, please submit them here.

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it for further problems.
