### ISSUE TITLE
Custom Volume Data Format Parser

### ISSUE THREAD

**Issue by gokseltokur** [keijiro/ComputeMarchingCubes#7]
First of all, great implementation!

I am using my custom volume data format want to parse it as stanford's but found nothing about data shape/format in the link that you attached in the readme. Or we can leave aside my data format, simply I have Texture3D with RGBA32 colors, I just want to save this as the stanford's. Do you have any advice?

**Comment by keijiro** [comment]
> I am using my custom volume data format want to parse it as stanford's but found nothing about data shape/format in the link that you attached in the readme.

The format is described in README.txt:

https://github.com/keijiro/ComputeMarchingCubes/tree/main/Assets/VolumeData/CThead

**Comment by keijiro** [comment]
I close this issue as resolved. Please reopen it for further problems.
